import type { AppState } from './types';

const ITEM_NAMES = [
  'AI Limiter',
  'Alien DNA Capsule',
  'Alien Protein',
  'Automated Wiring',
  'Bacon Agaric',
  'Beryl Nut',
  'Biomass',
  'Black Powder',
  'Blade Runners',
  'Blue Power Slug',
  'Cable',
  'Caterium Ingot',
  'Caterium Ore',
  'Chainsaw',
  'Circuit Board',
  'Coal',
  'Concrete',
  'Copper Ingot',
  'Copper Ore',
  'Copper Sheet',
  'Crude Oil',
  'Crystal Oscillator',
  'Empty Canister',
  'Encased Industrial Beam',
  'Fabric',
  'Fuel',
  'Gas Filter',
  'Gas Mask',
  'Gas Nobelisk',
  'Hatcher Remains',
  'Heavy Oil Residue',
  'High-Speed Connector',
  'Hog Remains',
  'Iron Ingot',
  'Iron Ore',
  'Iron Plate',
  'Iron Rebar',
  'Iron Rod',
  'Jetpack',
  'Leaves',
  'Limestone',
  'Liquid Biofuel',
  'Medicinal Inhaler',
  'Mercer Sphere',
  'Modular Frame',
  'Motor',
  'Mycelia',
  'Nobelisk',
  'Nobelisk Detonator',
  'Object Scanner',
  'Packaged Fuel',
  'Packaged Heavy Oil Residue',
  'Packaged Liquid Biofuel',
  'Packaged Oil',
  'Packaged Water',
  'Paleberry',
  'Parachute',
  'Petroleum Coke',
  'Plastic',
  'Polymer Resin',
  'Portable Miner',
  'Power Shard',
  'Pulse Nobelisk',
  'Purple Power Slug',
  'Quartz Crystal',
  'Quickwire',
  'Raw Quartz',
  'Reanimated SAM',
  'Rebar Gun',
  'Reinforced Iron Plate',
  'Rifle',
  'Rifle Ammo',
  'Rotor',
  'Rubber',
  'SAM',
  'SAM Fluctuator',
  'Screws',
  'Shatter Rebar',
  'Silica',
  'Smart Plating',
  'Smokeless Powder',
  'Solid Biofuel',
  'Spitter Remains',
  'Stator',
  'Steel Beam',
  'Steel Ingot',
  'Steel Pipe',
  'Stinger Remains',
  'Stun Rebar',
  'Sulfur',
  'Versatile Framework',
  'Water',
  'Wire',
  'Wood',
  'Xeno-Basher',
  'Xeno-Zapper',
  'Yellow Power Slug',
  'Zipline',
];

function uid(): string {
  return crypto.randomUUID();
}

export function createInitialState(): AppState {
  return {
    groups: [
      {
        id: uid(),
        title: 'All Items',
        color: { r: 33, g: 38, b: 45 },
        collapsed: false,
        items: ITEM_NAMES.map((name) => ({ id: uid(), name, checked: false })),
      },
    ],
  };
}
